# Generated by Django 4.0 on 2021-12-30 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend_list',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='friend_list',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recieve_request',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='recieve_request',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='sent_request',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='sent_request',
            name='to_user',
        ),
        migrations.DeleteModel(
            name='bill',
        ),
        migrations.DeleteModel(
            name='friend_list',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
        migrations.DeleteModel(
            name='recieve_request',
        ),
        migrations.DeleteModel(
            name='sent_request',
        ),
    ]
